version: "3.7"
services:
  redis:
    image: "redis:alpine"
    network_mode: "host"
  backend:
    image: water0641/ticket-backend-22th:1.1.1
    container_name: backend
    env_file:
      - .env
    network_mode: "host"
  front:
    image: david0218/ticket-front:1.0.6
    container_name: front
    network_mode: "host"
  admin:
    image: water0641/ticket-admin-22th:1.0.2
    container_name: admin
    network_mode: "host"
    # docker build water0641/ticket-nginx-22th:1.0.3 --platform linux/amd64 .
  nginx:
    network_mode: "host"
    depends_on:
      - backend
      - front
      - admin
    restart: always
    image: water0641/ticket-nginx-22th:1.0.3
